name = "Abused Debug Privilege by Arbitrary Parent Processes"

description = "Adversaries may bypass UAC mechanisms to elevate process privileges on system."
author = "Matt Suiche (@msuiche), Radovan Stevanovic"

references = [
    "https://image.slidesharecdn.com/kheirkhabarovoffzonefinal-181117201458/95/hunting-for-privilege-escalation-in-windows-environment-74-638.jpg",
    "https://attack.mitre.org/techniques/T1548/002/",
    "https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_abusing_debug_privilege.yml"
]

date = 2022-08-30
modified = 2022-08-30

tags = ["attack.privilege_escalation", "attack.defense_evasion"]

[[query]]
threat = "malicious"
mitre = ["T1548.002"]
gql="""
processObject(query:[
    {
      parentProcessName: { in: ["winlogon.exe", "services.exe", "lsass.exe", "csrss.exe", "smss.exe", "wininit.exe", "spoolsv.exe", "searchindexer.exe"]}
      processName: { in: ["powershell.exe", "pwsh.exe", "cmd.exe"] }
    },
  ]){
    processName
    processId
    commandLine
  }
"""